export const FETCH_CONTACTS = 'FETCH_CONTACTS';

export const FETCH_CONTACTS_FULFILLED = 'FETCH_CONTACTS_FULFILLED';

export const SAVE_CONTACT = 'SAVE_CONTACT';

export const SAVE_CONTACT_FULFILLED = 'SAVE_CONTACT_FULFILLED';

export const SAVE_CONTACT_REJECTED = 'SAVE_CONTACT_REJECTED';

export const SAVE_CONTACT_PENDING = 'SAVE_CONTACT_PENDING';

export const NEW_CONTACT = 'NEW_CONTACT';


